"""Bake Furina source crops into one fixed-grid PNG per action (requires Pillow)."""
import argparse
import json
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
CHARACTER = ROOT / "characters" / "furina"
RECIPE = CHARACTER / "animations" / "source-frames.json"
OUTPUT = CHARACTER / "animations" / "standard"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify existing sheets without writing")
    args = parser.parse_args()
    recipe = json.loads(RECIPE.read_text(encoding="utf-8"))
    width, height = recipe["cellWidth"], recipe["cellHeight"]
    columns, rows = recipe["columns"], recipe["rows"]
    images, counts, first_frames = {}, {}, []
    if not args.check:
        OUTPUT.mkdir(parents=True, exist_ok=True)
    for action, source_id in recipe["actions"].items():
        frames = recipe["sources"][source_id]
        assert 0 < len(frames) <= columns * rows, action
        sheet = Image.new("RGBA", (width * columns, height * rows))
        for index, frame in enumerate(frames):
            source_path = CHARACTER / frame["source"]
            if source_path not in images:
                images[source_path] = Image.open(source_path).convert("RGBA")
            x, y, w, h = (frame[key] for key in ("x", "y", "width", "height"))
            source = images[source_path]
            assert x >= 0 and y >= 0 and x + w <= source.width and y + h <= source.height, action
            scale = frame["scale"]
            crop = source.crop((x, y, x + w, y + h)).resize(
                (round(w * scale), round(h * scale)), Image.Resampling.NEAREST)
            cell = Image.new("RGBA", (width, height))
            cell.alpha_composite(crop, (
                round(width / 2 - frame["anchorX"] * scale),
                round(frame.get("targetY", 200) - frame["anchorY"] * scale)))
            sheet.alpha_composite(cell, ((index % columns) * width, (index // columns) * height))
        output = OUTPUT / f"{action}.png"
        if args.check:
            with Image.open(output) as actual:
                assert actual.size == sheet.size and actual.convert("RGBA").tobytes() == sheet.tobytes(), action
        else:
            sheet.save(output, optimize=True)
        counts[action] = len(frames)
        first_frames.append((action, sheet.crop((0, 0, width, height))))
    metadata = "// Generated by tools/build-furina-sheets.py.\nexport const standardSheetFrameCounts = " + json.dumps(counts, indent=2) + " as const;\n"
    metadata_path = CHARACTER / "standard-sheets.ts"
    if args.check:
        assert metadata_path.read_text(encoding="utf-8") == metadata
    else:
        metadata_path.write_text(metadata, encoding="utf-8")
        preview = Image.new("RGBA", (width * 6, (height + 24) * ((len(first_frames) + 5) // 6)), (35, 45, 65, 255))
        draw = ImageDraw.Draw(preview)
        for index, (action, cell) in enumerate(first_frames):
            x, y = (index % 6) * width, (index // 6) * (height + 24)
            draw.text((x + 8, y + 4), action, fill="white")
            preview.alpha_composite(cell, (x, y + 24))
        preview.save(ROOT / "docs" / "standard-action-sheets.png")
    print(f"{'Verified' if args.check else 'Built'} {len(counts)} sheets: {width * columns}x{height * rows}, cells {width}x{height}")


if __name__ == "__main__":
    main()
